INSERT INTO candidates (name, experience_years, skills) VALUES ('Eula Lakin-Ward', 5, 'Safety Compliance, Sustainability');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Shane Hilpert', 13, 'Safety Compliance, Team Leadership, Lean Manufacturing, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Dr. Eleanor Tillman', 9, 'Sustainability, Lean Manufacturing');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Penny Batz', 7, 'Six Sigma, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Raymond Lindgren II', 7, 'Lean Manufacturing, Six Sigma, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Mr. Roger Mills', 14, 'Lean Manufacturing, Team Leadership, Sustainability, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Walter Grimes', 14, 'Safety Compliance, Six Sigma, Team Leadership, Sustainability');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Dr. Nathan Will', 17, 'Team Leadership, Lean Manufacturing');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Alexis Schneider', 8, 'Team Leadership, Lean Manufacturing, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Minnie Hills', 3, 'Sustainability, Team Leadership, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Angel Fadel', 19, 'Sustainability, Team Leadership, Six Sigma, Lean Manufacturing');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Jeff Stokes-Lebsack', 17, 'Six Sigma, Lean Manufacturing, Team Leadership, Sustainability');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Samuel Harvey', 6, 'Safety Compliance, Sustainability, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Ramona Durgan', 6, 'Six Sigma, Lean Manufacturing, Sustainability, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Katherine Hodkiewicz', 8, 'Lean Manufacturing, Team Leadership, Safety Compliance, Sustainability');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Adrian Turcotte', 17, 'Sustainability, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Jill Daugherty', 17, 'Lean Manufacturing, Six Sigma, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Elvira Willms', 10, 'Safety Compliance, Sustainability');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Sharon Zboncak', 6, 'Sustainability, Lean Manufacturing, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Billie Hoppe', 14, 'Safety Compliance, Lean Manufacturing, Sustainability, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Belinda Langosh', 16, 'Six Sigma, Lean Manufacturing, Sustainability, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Jonathan Ebert', 5, 'Team Leadership, Lean Manufacturing, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Clifton Toy', 13, 'Safety Compliance, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Guadalupe Frami', 3, 'Safety Compliance, Lean Manufacturing, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Shawna Schneider', 11, 'Sustainability, Six Sigma, Lean Manufacturing, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Bethany Torp', 16, 'Six Sigma, Lean Manufacturing, Team Leadership, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Bennie Bechtelar', 13, 'Team Leadership, Lean Manufacturing');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Billie Kovacek V', 3, 'Safety Compliance, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Casey Orn', 18, 'Six Sigma, Sustainability');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Amanda Nitzsche', 12, 'Sustainability, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Nathan Gulgowski', 2, 'Six Sigma, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Teri West DVM', 10, 'Team Leadership, Six Sigma, Lean Manufacturing');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Gerald Walsh', 11, 'Team Leadership, Sustainability, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Elmer Jaskolski', 3, 'Lean Manufacturing, Safety Compliance, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Anna Kirlin', 18, 'Team Leadership, Sustainability, Safety Compliance, Six Sigma');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Antonia Leuschke', 16, 'Team Leadership, Six Sigma, Lean Manufacturing');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Olive Rodriguez', 9, 'Sustainability, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Bonnie Collier DVM', 6, 'Six Sigma, Team Leadership, Safety Compliance');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Rosa Stanton III', 13, 'Lean Manufacturing, Team Leadership');
INSERT INTO candidates (name, experience_years, skills) VALUES ('Gregg Price', 18, 'Sustainability, Lean Manufacturing');
